version: '2.3'
services:
  rabbitmq:
    networks:
    - gocrawler-network
    image: "rabbitmq"
    restart: always
  cassandra:
    networks:
    - gocrawler-network
    image: "cassandra:latest"
    restart: always
  ptt-consumer:
    depends_on:
    - rabbitmq
    - cassandra
    networks:
    - gocrawler-network
    environment:
    - GO_CRAWLER_RABBITMQ_HOST=rabbitmq
    - GO_CRAWLER_RABBITMQ_PORT=5672
    - GO_CRAWLER_RABBITMQ_ACCOUNT=guest
    - GO_CRAWLER_RABBITMQ_PASSWORD=guest
    - GO_CRAWLER_CASSANDRA_HOST=cassandra
    - GO_CRAWLER_CASSANDRA_PORT=9042
    - GO_CRAWLER_SERVER_RUNMODE=debug
    - GO_CRAWLER_CONSUMER_TYPE=ptt
    image: "ekko771/crawler-consumer:v2"
    restart: always
  dcard-consumer:
    depends_on:
    - rabbitmq
    - cassandra
    networks:
    - gocrawler-network
    environment:
    - GO_CRAWLER_RABBITMQ_HOST=rabbitmq
    - GO_CRAWLER_RABBITMQ_PORT=5672
    - GO_CRAWLER_RABBITMQ_ACCOUNT=guest
    - GO_CRAWLER_RABBITMQ_PASSWORD=guest
    - GO_CRAWLER_CASSANDRA_HOST=cassandra
    - GO_CRAWLER_CASSANDRA_PORT=9042
    - GO_CRAWLER_SERVER_RUNMODE=debug
    - GO_CRAWLER_CONSUMER_TYPE=dcard
    image: "ekko771/crawler-consumer:v2"
    restart: always
  go-crawler-service:
    depends_on:
      - rabbitmq
      - cassandra
      - ptt-consumer
      - mongo
      - serverfluent
    networks:
    - gocrawler-network
    ports:
    - "8080:8080"
    environment:
    - GO_CRAWLER_SERVER_HOST=0.0.0.0
    - GO_CRAWLER_SERVER_PORT=8080
    - GO_CRAWLER_SERVER_debug=release
    - GO_CRAWLER_RABBITMQ_HOST=rabbitmq
    - GO_CRAWLER_RABBITMQ_PORT=5672
    - GO_CRAWLER_RABBITMQ_ACCOUNT=guest
    - GO_CRAWLER_RABBITMQ_PASSWORD=guest
    - GO_CRAWLER_CASSANDRA_HOST=cassandra
    - GO_CRAWLER_CASSANDRA_PORT=9042
    - GO_CRAWLER_FLUENTD_HOST=serverfluent
    - GO_CRAWLER_FLUENTD_PORT=24224
    image: "ekko771/go-crawler-service:v2"
    restart: always
  mongo:
    image: mongo
    restart: always
    ports: 
      - 27017:27017
    networks:
    - gocrawler-network
  serverfluent:
    image: ekko771/fluentd-mogo:v1
    volumes:
      - ./fluentd/server_fluentd.conf:/fluentd/etc/fluent.conf
    ports: 
      - 24224:24224
    networks:
    - gocrawler-network
networks:
  gocrawler-network:
    driver: bridge
