version: '2.3'

services:
  jaeger:
    networks:
    - $DEFAULT_NETWORK
    image: "jaegertracing/all-in-one:latest"
    restart: always
    ports: 
      - 16686:16686
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
  rabbitmq:
    networks:
    - $DEFAULT_NETWORK
    image: "rabbitmq"
    restart: always

  cassandra:
    networks:
    - $DEFAULT_NETWORK
    image: "cassandra:latest"
    restart: always

  mongo:
    image: mongo
    restart: always
    ports: 
      - 27017:27017
    networks:
    - $DEFAULT_NETWORK

  serverfluent:
    image: ekko771/fluentd-mogo:v1
    volumes:
      - ./fluentd/server_fluentd.conf:/fluentd/etc/fluent.conf
      - ./GoCrawler:/var/log/GoCrawler
    ports: 
      - 24224:24224
    networks:
    - $DEFAULT_NETWORK

  ptt-consumer:
    depends_on:
    - rabbitmq
    - cassandra
    networks:
    - $DEFAULT_NETWORK
    environment:
    - GO_CRAWLER_RABBITMQ_HOST=rabbitmq
    - GO_CRAWLER_RABBITMQ_PORT=5672
    - GO_CRAWLER_RABBITMQ_ACCOUNT=guest
    - GO_CRAWLER_RABBITMQ_PASSWORD=guest
    - GO_CRAWLER_CASSANDRA_HOST=cassandra
    - GO_CRAWLER_CASSANDRA_PORT=9042
    - GO_CRAWLER_SERVER_RUNMODE=debug
    - GO_CRAWLER_CONSUMER_TYPE=ptt
    - GO_CRAWLER_JAEGER_HOST=24224
    - GO_CRAWLER_JAEGER_PORT=jaeger
    - GO_CRAWLER_JAEGER_OPEN=true
    image: "ekko771/crawler-consumer:v4"
    volumes:
      - ./GoCrawler:/var/log/GoCrawler
    restart: always
  dcard-consumer:
    depends_on:
    - rabbitmq
    - cassandra
    networks:
    - $DEFAULT_NETWORK
    environment:
    - GO_CRAWLER_RABBITMQ_HOST=rabbitmq
    - GO_CRAWLER_RABBITMQ_PORT=5672
    - GO_CRAWLER_RABBITMQ_ACCOUNT=guest
    - GO_CRAWLER_RABBITMQ_PASSWORD=guest
    - GO_CRAWLER_CASSANDRA_HOST=cassandra
    - GO_CRAWLER_CASSANDRA_PORT=9042
    - GO_CRAWLER_SERVER_RUNMODE=debug
    - GO_CRAWLER_CONSUMER_TYPE=dcard
    - GO_CRAWLER_JAEGER_HOST=24224
    - GO_CRAWLER_JAEGER_PORT=jaeger
    - GO_CRAWLER_JAEGER_OPEN=true
    image: "ekko771/crawler-consumer:v4"
    volumes:
      - ./GoCrawler:/var/log/GoCrawler
    restart: always

  go-crawler-service-1:
    depends_on:
      - rabbitmq
      - cassandra
      - ptt-consumer
      - mongo
      - serverfluent
    networks:
    - $DEFAULT_NETWORK
    environment:
    - GO_CRAWLER_SERVER_HOST=0.0.0.0
    - GO_CRAWLER_SERVER_PORT=8080
    - GO_CRAWLER_SERVER_debug=release
    - GO_CRAWLER_RABBITMQ_HOST=rabbitmq
    - GO_CRAWLER_RABBITMQ_PORT=5672
    - GO_CRAWLER_RABBITMQ_ACCOUNT=guest
    - GO_CRAWLER_RABBITMQ_PASSWORD=guest
    - GO_CRAWLER_CASSANDRA_HOST=cassandra
    - GO_CRAWLER_CASSANDRA_PORT=9042
    - GO_CRAWLER_FLUENTD_HOST=serverfluent
    - GO_CRAWLER_FLUENTD_PORT=24224
    - GO_CRAWLER_JAEGER_HOST=24224
    - GO_CRAWLER_JAEGER_PORT=jaeger
    - GO_CRAWLER_JAEGER_OPEN=true
    image: "ekko771/go-crawler-service:v4"
    volumes:
      - ./GoCrawler:/var/log/GoCrawler
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.go-crawler-service-1.entrypoints=web"
      - "traefik.http.routers.go-crawler-service-1.rule=Host(`gocrawler1.$MY_DOMAIN`)"
      - "traefik.http.services.go-crawler-service-1.loadbalancer.server.port=8080"

  go-crawler-service-2:
    depends_on:
      - rabbitmq
      - cassandra
      - ptt-consumer
      - mongo
      - serverfluent
    networks:
    - $DEFAULT_NETWORK
    environment:
    - GO_CRAWLER_SERVER_HOST=0.0.0.0
    - GO_CRAWLER_SERVER_PORT=8080
    - GO_CRAWLER_SERVER_debug=release
    - GO_CRAWLER_RABBITMQ_HOST=rabbitmq
    - GO_CRAWLER_RABBITMQ_PORT=5672
    - GO_CRAWLER_RABBITMQ_ACCOUNT=guest
    - GO_CRAWLER_RABBITMQ_PASSWORD=guest
    - GO_CRAWLER_CASSANDRA_HOST=cassandra
    - GO_CRAWLER_CASSANDRA_PORT=9042
    - GO_CRAWLER_FLUENTD_HOST=serverfluent
    - GO_CRAWLER_FLUENTD_PORT=24224
    - GO_CRAWLER_JAEGER_HOST=24224
    - GO_CRAWLER_JAEGER_PORT=jaeger
    - GO_CRAWLER_JAEGER_OPEN=true
    image: "ekko771/go-crawler-service:v4"
    volumes:
      - ./GoCrawler:/var/log/GoCrawler
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.go-crawler-service-2.entrypoints=web"
      - "traefik.http.routers.go-crawler-service-2.rule=Host(`gocrawler2.$MY_DOMAIN`)"
      - "traefik.http.services.go-crawler-service-2.loadbalancer.server.port=8080"

networks:
  traefik_net:
    external:
      name: $DEFAULT_NETWORK
