server:
  host: "127.0.0.1"
  port: 8080
  runMode: "debug"
rabbitmq:
  host: "127.0.0.1"
  port: 5672
  account: "guest"
  password: "guest"
cassandra:
  host: "127.0.0.1"
  port: 9042
fluentd:
  host: "127.0.0.1"
  port: 24224
consumer:
  type: "ptt"
jaeger:
  open: true
  host: "127.0.0.1"
  port: 6831
db:
  host: "127.0.0.1"
  port: 5432
  user: "postgres"
  password: "password"
  dbname: "backend_admin"
  sslmode: "disable"
redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
 